<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\BundleOptionSelection\Block\Selection;
use Magento\Framework\View\TemplateEngine\Php;

/** @var Php $this */
/** @var Selection $block */
?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "bundleOptionSelection": {
                "index": <?= /* @noEscape */ $block->getIndex(); ?>
            }
        }
    }
</script>
